runner: "mt_episode"

# only use for initializing action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

# update the target network every _ steps
target_update_interval: 80

# use the Q_Learner to train
agent_output_type: "q"
learner: "odis_learner"
double_q: True
mixer: "mt_qattn"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "mto"

# agent type
agent: "mt_odis"

# mac
mac: "mt_odis_mac"

# params about trans mixing network
entity_embed_dim: 64
attn_embed_dim: 8
skill_dim: 3
c_step: 1
beta: 0.001
coef_conservative: 5.0
coef_dist: 5.0
pretrain_steps: 15000
pretrain: True

head: 1
depth: 1

# params about observation decomposition
id_length: 4
max_agent: 15
