# --- Transfer MATD3+BC specific parameters ---

runner: "mt_episode"

buffer_size: 50000
# update the target network every {} episodes
target_update_interval_or_tau: .005

obs_agent_id: True
obs_last_action: True
obs_individual_obs: True

critic_individual_obs: True
critic_last_action: False
critic_agent_id: True

# mac
mac: "mt_maddpg_mac"
batch_size: 32
lr: 0.0003

standardise_returns: False
standardise_rewards: True

# agent type
agent: "mt_rnn"

learner: "mt_matd3_learner"
agent_output_type: "pi_logits"
hidden_dim: 128
critic_type: "mt_maddpg_critic"


# params about observation decomposition
id_length: 4
max_agent: 15


# params about mt mixing network
entity_embed_dim: 64
attn_embed_dim: 8
head: 1

optim_type: "adam"
actor_freq: 2
td3_alpha: 2.5

name: "tr_matd3_bc"


offline_train_steps: 205
online_train_steps: 205 # for online train

# 0: not trained, save pretraining model and not load or load from pretraining model; 
ckpt_stage: 0
# checkpoint_path: "/home/amax/xyc/MATr/offpymarl/results/transfer/lbforaging/lbf_test/lbforaging:Foraging-5x5-2p-2f-coop-v2-expert+lbforaging:Foraging-5x5-3p-2f-coop-v2-expert/tr_sf/seed_1_tr_sf_2024-12-31_15-21-34/models/pretrain" # 8 phi x 8 dim
