# --- Transfer with SF specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 0.0
epsilon_finish: 0.0
epsilon_anneal_time: 1

runner: "mt_episode" # the same way to handle multi-task info in runners

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 0.005

# learner />
agent_output_type: "q" # regard psi as q's
learner: "tr_sf_learner"
double_q: True
# mixer: tr_dmaq_qatten # NOTE vdn(tr_vdn), vdn-with-bias, 1-qmix(tr_qatten), qplex(tr_dmaq_qatten)
mixer: tr_dmaq_qatten
task_emb_std: 0.1
cql_alpha: 1.0 # largely depend on the quality of dataset
cql_type: "base"

mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64
mixing_head: 4
mask_dead: False
attend_reg_coef: 0.001
weighted_head: False

# params about mt inputs mixing network
entity_embed_dim: 64
attn_embed_dim: 8
head: 1

# params about observation decomposition
id_length: 4
max_agent: 15

# ckpt_stage: 0
# optim_type: "sgd"
# lr: 0.005 # 0.005 -> 0.0001
# pretrain_batch_size: 32 # 32 -> 8
# pretrain_steps: 100005 # 100005 -> cont
# checkpoint_path: /home/amax/xyc/MATr/offpymarl/results/transfer/lbforaging/lbf_test/lbforaging:Foraging-5x5-2p-2f-coop-v2-expert+lbforaging:Foraging-5x5-3p-2f-coop-v2-expert+lbforaging:Foraging-5x5-2p-3f-coop-v2-expert+lbforaging:Foraging-5x5-4p-2f-coop-v2-expert/tr_sf/seed_1_tr_sf_2025-03-14_13-49-55/models/pretrain
# load_step: 100005
# test_interval: 5000
# log_interval: 5000
# runner_log_interval: 5000
# learner_log_interval: 5000

ckpt_stage: 1
offline_train_steps: 50005
# checkpoint_path: 
# load_step: 
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000

# ckpt_stage: 2
# online_train_steps: 10005

# ckpt_stage: 3
# optim_type: "sgd"
# lr: 1
# adapt_steps: 1005
# checkpoint_path: /home/amax/xyc/MATr/offpymarl/results/transfer/lbforaging/lbf_test/lbforaging:Foraging-5x5-2p-2f-coop-v2-expert+lbforaging:Foraging-5x5-3p-2f-coop-v2-expert+lbforaging:Foraging-5x5-2p-3f-coop-v2-expert+lbforaging:Foraging-5x5-4p-2f-coop-v2-expert/tr_sf/seed_3_tr_sf_2025-03-15_10-45-21/models/offline
# load_step: 40011
# test_interval: 100
# log_interval: 100
# runner_log_interval: 100
# learner_log_interval: 100

# </ learner

# agent type
agent: "tr_sf_rnn"
phi_dim: 64

# mac
mac: "tr_basic_mac"

standardise_returns: False
standardise_rewards: True

name: "tr_sf"
