# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "msz_small_expert"
# define train tasks and test tasks
train_tasks: ["3m", "2s3z"]
train_tasks_data_quality: {
    "3m": "expert",
    "2s3z": "expert",
}

tasks_offline_bottom_data_paths: {
  "3m": "/home/amax/xyc/MATr/offpymarl/dataset/sc2/3m/expert/seed_1_maa2c_2024-12-15_15-22-03",
  "2s3z": "/home/amax/xyc/MATr/offpymarl/dataset/sc2/2s3z/expert/seed_1_maa2c_2024-12-15_15-22-06",
}

test_tasks: ["3m", "2s3z"]