# ----- test lbf transfer setting config -----

# get env information
env: "sc2"

# get task information
task: "sc2_test"
# define train tasks and test tasks
train_tasks: [
  "3m", "4m"
]
train_tasks_data_quality: {
  "3m": "expert",
  "4m": "expert",
}

tasks_offline_bottom_data_paths: {
  "lbforaging:Foraging-5x5-2p-2f-coop-v2": "/home/amax/xyc/MATr/offpymarl/dataset/lbforaging/Foraging-5x5-2p-2f-coop-v2/expert/seed_1_qmix_2024-12-12_10-24-15",
  "lbforaging:Foraging-5x5-3p-2f-coop-v2": "/home/amax/xyc/MATr/offpymarl/dataset/lbforaging/Foraging-5x5-3p-2f-coop-v2/expert/seed_1_qmix_2024-12-12_10-24-21",
}

trans_tasks: ["5m", "7m"]
