# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "sc2_marines"
# define train tasks and test tasks
train_tasks: ["3m", "5m_vs_6m", "9m_vs_10m"]
train_tasks_data_quality: {
    "3m": "expert",
    "5m_vs_6m": "expert",
    "9m_vs_10m": "expert",
}

tasks_offline_bottom_data_paths: {
  "3m": "dataset/sc2/3m/expert/seed_1_qmix_2024-12-15_14-58-34",
  "5m_vs_6m": "dataset/sc2/5m_vs_6m/expert/seed_3407_qmix_2025-04-20_10-21-51",
  "9m_vs_10m": "dataset/sc2/9m_vs_10m/expert/seed_3407_qmix_2025-04-20_19-45-19",
}
test_tasks: ["3m", "5m_vs_6m", "9m_vs_10m", "4m", "5m", "10m", "12m", "7m_vs_8m", "8m_vs_9m", "10m_vs_11m", "10m_vs_12m", "13m_vs_15m"] # evaluate only

trans_tasks: []
